import google.generativeai as genai
import os

class ReadmeAgent:
    def __init__(self):
        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        # Fixed Model Name: 1.5-flash is stable and high-quota
        self.model = genai.GenerativeModel("gemini-2.5-flash")

    def generate_readme(self, project_data: dict, dependency_graph_text: str) -> str:
        summary = project_data['summary']
        
        # Create a simplified file list for context
        file_list = "\n".join([f"- {f} ({m['ext']})" for f, m in project_data['files'].items()])
        
        prompt = f"""
# ROLE
You are a Principal Software Architect.

# TASK
Synthesize a technical README.md for 'Project Cypherweave'.

# PROJECT METADATA
- Total Files: {summary['total_files']}
- Stack Breakdown: {summary['python']} Python, {summary['web']} Web (React/TS).

# DETECTED DEPENDENCIES (Use this for the Diagram)
{dependency_graph_text}

# FILE STRUCTURE
{file_list}

# REQUIRED SECTIONS
1. **Overview**: High-level purpose of the application.
2. **Architecture**: 
   - Generate a `mermaid` graph TD based strictly on the "DETECTED DEPENDENCIES" list above.
   - If the graph is empty, infer the flow based on file names (e.g., Page -> Component).
3. **Component Map**: Group files logically (e.g., "Core Logic", "UI Components", "API Routes").
4. **Tech Stack**: Inferred table of technologies.

# INNOVATION FOOTER
Add a note that this documentation was autonomously generated by the "Nasiko Self-Reflective Agent".
"""
        try:
            response = self.model.generate_content(prompt)
            return response.text
        except Exception as e:
            return f"Error generating README: {e}"